lestarch: initial style guidelines
nasa/fprime pull request #1197
Opened 2022-01-03 20:27 UTC by LeStarch

| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Adds in style guide.

## Rationale

Opening up other contributors.

## Testing/Review Recommendations

Just documentation.

## Future Work

More documentation.

2022-01-03 21:07 UTC, timcanham requested changes

2022-01-03 21:07 UTC, timcanham commented on docs/UsersGuide/dev/code-style.md
> +
4. Avoid multiple inheritance paths that derive from a common base class (the diamond problem): https://www.cprogramming.com/tutorial/virtual_inheritance.html

2022-01-04 00:45 UTC, timcanham approved these changes

2022-01-04 01:26 UTC, LeStarch commented
Noting @timcanham approval.  Pushing to fix spelling and nothing more.

2022-01-04 01:39 UTC, Joshua-Anderson commented on docs/UsersGuide/dev/code-style.md
> +2. Use of `std::atomic` is known to not work is some cases. Use is avoided.
Spelling fix: s/is/in/

2022-01-04 18:26 UTC, LeStarch commented
Fixed issues, changes since review approval:

1. spelling fix for new webaddress
2. is->in as requested.

2022-01-04 18:26 UTC, merged