Clean autocoders code
nasa/fprime pull request #1240
Opened 2022-01-26 15:05 UTC by iw4p

| | |
|:---|:---|
|**_Originating Project/Creator_**| iw4p |
|**_Affected Component_**| Autocoder  |
|**_Affected Architectures(s)_**| Python |
|**_Related Issue(s)_**| N/A |
|**_Has Unit Tests (y/n)_**| exist |
|**_Builds Without Errors (y/n)_**| Y |
|**_Unit Tests Pass (y/n)_**| Y |
|**_Documentation Included (y/n)_**| Y |

---
## Change Description
Check and lint codes via pylint to find out what's missing or wrong and clean the code.

## Rationale
Fixed bugs.

## Testing/Review Recommendations

Built with `cmake ../ -DCMAKE_BUILD_TYPE=TESTING` and `make check`.

## Future Work

Nothing for now.

2022-02-08 17:42 UTC, LeStarch requested changes
Many of the returns that were removed were necessary for the code to function.  In all cases where a return is on an error branch they need to be restored.

2022-02-08 17:42 UTC, LeStarch commented on Autocoders/Python/bin/gds_dictgen.py
> -        return
Return is necessary here.

2022-02-09 13:08 UTC, iw4p commented on Autocoders/Python/bin/gds_dictgen.py
> -        return
Oh, I think it's fine now.

2022-02-14 19:03 UTC, LeStarch commented on Autocoders/Python/bin/implgen.py
> -        return
This return is still removed, which will change the behavior

2022-02-14 22:49 UTC, iw4p commented
> Two more missing returns. Other than that, it looks good!

I think it's fine now, Thank you.

2022-02-15 23:02 UTC, LeStarch approved these changes

2022-02-16 00:16 UTC, merged