Update/rgd fix
nasa/fprime pull request #1467
Opened 2022-05-20 02:50 UTC by timcanham

| | |
|:---|:---|
|**_Originating Project/Creator_**| JPL Infrastructure work |
|**_Affected Component_**| `Svc/RateGroupDriver` |
|**_Affected Architectures(s)_**| All |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**| y |
|**_Builds Without Errors (y/n)_**| y |
|**_Unit Tests Pass (y/n)_**| y |
|**_Documentation Included (y/n)_**| y |

---
## Change Description

The rate group divider array was moved from the constructor to a new `configure()` function.

## Rationale

This makes the constructor compliant with the FPP code generator for constructors, simplifying the FPP statements

## Testing/Review Recommendations

Re-run unit tests and verify Ref app still runs.

## Future Work

None.

2022-05-20 05:15 UTC, LeStarch approved these changes
Looks like what I'd expect.  Is there a reason for the "Draft" status?

2022-05-20 17:25 UTC, timcanham commented
I make them draft so I can do a final diff in the browser...

2022-05-23 16:26 UTC, bocchino requested changes
Looks good, but please review the comment.

2022-05-23 16:26 UTC, bocchino commented on RPI/Top/instances.fpp
> +    phase Fpp.ToCpp.Phases.configComponents """
I don't think we want to move the array declaration from the `configObjects` phase to the `configComponents` phase.

* The `configObjects` phase is for declaring static objects and has program-lifetime scope
* The `configComponents` phase is inside a function and has local function scope

Maybe it's OK to declare the array inside the function, if the array values get copied by the call, but this feels like a change we don't want to do.

2022-05-24 03:36 UTC, bocchino approved these changes
Looks good!

2022-05-24 03:41 UTC, timcanham commented
The 'configure()' function actually dies copy it, but it makes sense to keep it consistent with 'ActiveRateGroup'. Still needs to be tested, so don't merge it yet.

2022-05-24 04:27 UTC, timcanham commented
OK - Linux testing done.

2022-05-27 19:43 UTC, merged