Update to Svc::Framer design and implementation
nasa/fprime pull request #1586
Opened 2022-07-22 22:16 UTC by bocchino

After design review and code review.

2022-07-22 22:43 UTC, kevin-f-ortega approved these changes
LGTM. We went through this together.

2022-07-25 17:13 UTC, arizvi786 approved these changes
@bocchino great work!

2022-07-26 00:00 UTC, LeStarch requested changes
One minor spelling issue

2022-07-26 03:47 UTC, bocchino commented on Svc/Framer/Framer.fpp
> +  @ A component for deframing input for transmission to the ground
Good catch, fixed!

2022-07-26 03:56 UTC, LeStarch approved these changes

2022-07-26 16:57 UTC, LeStarch commented
## Pre-CI Checks: Must perform before launching CI
- [x] No obviously malicious code introduced
- [ x PR is against `devel`. Use `Edit -> change branch` to fix, or close PR.

## Code Review
- [x] Code follows flight software quality guidelines
- [x] Changes are of reasonable length for review

## Procedural Checks
- [x] PR passes CI
- [x] Accept with `squash-and-merge`

2022-07-26 16:57 UTC, merged

2022-07-27 01:54 UTC, jsoref commented on Svc/Framer/docs/sdd.md
> +<img src="img/top/file.png" width=1000/>
Fwiw, afaict this file (`file.png`) is ambiguous and broke the autodocumentation (which flattens files into a single directory).

I've posted #1599 which renames it. (I can't hang a comment on an image file, so I'm hanging it here where it's being used.)