fixes old autocoder printf types to newly setup types
nasa/fprime pull request #1799
Opened 2022-12-06 19:30 UTC by LeStarch

| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Fixes the old autocoder output to use correct `printf` output specifiers for the new types system.

2022-12-06 21:51 UTC, bocchino requested changes
See comments. The type of the printf specifier needs to match the type of the value.

2022-12-06 21:51 UTC, bocchino commented on Autocoders/Python/src/fprime_ac/generators/templates/component/cpp.tmpl
> +          "%s_${instance}_OutputPort[%" PRI_FwIndexType "]",
Similar comment here and for the rest of the changes. Make sure that in each case, the type of the printf specifier matches the type of the value.

2022-12-06 21:53 UTC, bocchino commented on Autocoders/Python/src/fprime_ac/generators/templates/component/cpp.tmpl
> +          "%s_${instance}_InputPort[%" PRI_FwIndexType "]",
Or you could use PRI_FwNativeIntType here.

2022-12-06 22:39 UTC, gjwatney approved these changes

2022-12-07 19:21 UTC, bocchino approved these changes
Looks good!

2022-12-07 19:28 UTC, gjwatney approved these changes

2022-12-07 19:32 UTC, merged