Update/type demo
nasa/fprime pull request #1937
Opened 2023-03-17 23:13 UTC by LeStarch

| | |
|:---|:---|
|**_Originating Project/Creator_**| Infrastructure |
|**_Affected Component_**| Complex Types |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  #1913 |
|**_Has Unit Tests (y/n)_**| n  |
|**_Builds Without Errors (y/n)_**| y |
|**_Unit Tests Pass (y/n)_**| y |
|**_Documentation Included (y/n)_**| n |

---
## Change Description

Adds in a type demo component that has complex commands and parameters!

## Rationale

To support complex commanding we need a component that has such commands and parameters.

## Testing/Review Recommendations

Test with: fprime-community/fprime-gds#122

## Future Work

Make recursive dictionary generation work (complete fix for #1913)

2023-03-17 23:17 UTC, thomas-bc commented
@LeStarch cleanest way to get CppCheck and CppLint scans to run will be to rebase locally on top of `devel` and push the changes to your PR, I think.

2023-03-17 23:32 UTC, bocchino commented
This is very cool!

2023-03-21 01:40 UTC, timcanham requested changes
Is it worth doing something with the unused arguments?

2023-03-21 01:40 UTC, timcanham commented on Ref/TypeDemo/TypeDemo.cpp
> +                                                U8 repeat,
repeat is never used?

2023-03-21 01:40 UTC, timcanham commented on Ref/TypeDemo/TypeDemo.cpp
> +                                                      U8 repeat,
repeat is never used?

2023-03-21 01:40 UTC, timcanham commented on Ref/TypeDemo/TypeDemo.cpp
> +                                                    U8 repeat,
repeat is never used?

2023-03-21 01:40 UTC, timcanham commented on Ref/TypeDemo/TypeDemo.cpp
> +                                                          U8 repeat,
repeat is never used?

2023-03-22 21:48 UTC, timcanham approved these changes

2023-03-31 20:41 UTC, merged