Update BufferAccumulator to FPv3
nasa/fprime pull request #1944
Opened 2023-03-23 23:12 UTC by kubiak-jpl

| | |
|:---|:---|
|**_Originating Project/Creator_**| @kubiak-jpl |
|**_Affected Component_**| BufferAccumulator |
|**_Affected Architectures(s)_**| N/A |
|**_Related Issue(s)_**| N/A |
|**_Has Unit Tests (y/n)_**| y |
|**_Builds Without Errors (y/n)_**| y |
|**_Unit Tests Pass (y/n)_**| y |
|**_Documentation Included (y/n)_**| n |

---
## Change Description

1. Update BufferAccumulator to FPv3
2. Add the BA_DrainBuffers command to drain a fixed number of buffers from the internal FIFO

## Rationale

Allows existing BufferAccumulator code to be using in FP deployments

## Testing/Review Recommendations

## Future Work

Additional documentation work is necessary

2023-03-28 15:11 UTC, FabrizioSandri commented on Svc/BufferAccumulator/ArrayFIFOBuffer.cpp
> +    FW_ASSERT(dequeueIndex < this->capacity, enqueueIndex);
Would it be more appropriate to pass `dequeueIndex` instead of `enqueueIndex` as the second argument to `FW_ASSERT ?

2023-04-13 02:01 UTC, timcanham requested changes

2023-04-17 20:30 UTC, kubiak-jpl commented
@timcanham I update the comments in the fpp file.

@timcanham @LeStarch Do the CodeQL warnings need to be addressed? I'm not convinced they point to anything worth addressing

2023-04-27 04:48 UTC, LeStarch commented
@timcanham is this ready to go?

2023-04-27 23:33 UTC, merged