Update/passive rg
nasa/fprime pull request #2051
Opened 2023-05-26 23:49 UTC by LeStarch

| | |
|:---|:---|
|**_Originating Project/Creator_**| |
|**_Affected Component_**|  |
|**_Affected Architectures(s)_**|  |
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Builds Without Errors (y/n)_**|  |
|**_Unit Tests Pass (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Adds a passive rate group!

2023-05-27 00:43 UTC, ThibFrgsGmz commented
Wouldn't it be better to have a sequence diagram in mermaid?

2023-05-29 02:08 UTC, timcanham requested changes
Leftover files, old headers and other minor comments.

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/docs/PassiveRateGroup.md
> +# PassiveRateGroup Component Dictionary
These are artifacts of the old make system that were autogenerated. Were you planning to add the autogeneration back in?

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/docs/sdd.md
> +`Svc::PassiveRateGroup` is an passive component that drives a set of components connected to `Svc::Sched` output ports. It contains an synchronous input `Svc::Cycle` port that drives all the operatio
Maybe this was originally my poor writing, but change the second to last sentence to say "passing an argument specified in the supplied context list."

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/test/mod.mk
> +#
delete?

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/test/ut/PassiveRateGroupImplTester.cpp
> +/*
Remove ITAR headers.

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/test/ut/Readme.txt
> +This test can be run by executing the following:
Remove file

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/test/ut/mod.mk
> +#
Remove

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/test/ut/runtest_CYGWIN
> +#!/bin/sh
remove

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/test/ut/runtest_DARWIN
> +#!/bin/sh
remove

2023-05-29 02:08 UTC, timcanham commented on Svc/PassiveRateGroup/test/ut/runtest_LINUX
> +#!/bin/sh
remove

2023-05-29 18:58 UTC, LeStarch commented
@timcanham  ready for re-review.  Your comments and @ThibFrgsGmz's comments addressed.

2023-05-29 23:00 UTC, ThibFrgsGmz commented on Svc/PassiveRateGroup/docs/sdd.md
> +Design Checklist | [Link](Checklist_Design.xlsx)
All links are broken, isn'it ?

2023-05-30 14:32 UTC, timcanham approved these changes

2023-05-30 18:07 UTC, LeStarch commented on Svc/PassiveRateGroup/docs/sdd.md
> +Design Checklist | [Link](Checklist_Design.xlsx)
Fixed links.

2023-05-30 18:08 UTC, merged