Add stream crossover component
nasa/fprime pull request #2070
Opened 2023-06-05 16:34 UTC by ethancheez

Add stream crossover component to enable connection from ByteStreamRecv to ByteStreamSend

2023-06-05 16:42 UTC, timcanham commented
![image](https://github.com/nasa/fprime/assets/8086374/938857ef-6b62-4d47-97be-65b8dff7fe4c)

2023-06-05 17:38 UTC, LeStarch requested changes
We should do the following:
1. Fix this spelling error (add `ethanechee` to `expect.txt`)
2. Handle the send return value: emit an event.  
3. Could we add a UT to test this?

2023-06-05 17:38 UTC, LeStarch commented on Drv/StreamCrossover/StreamCrossover.cpp
> +    this->streamOut_out(0, recvBuffer);
@ethancheez we should check these return values.  Either performing a re-try, or emitting a log or event message.

2023-06-08 19:49 UTC, LeStarch commented on Drv/StreamCrossover/StreamCrossover.cpp
> +        const Drv::RecvStatus &recvStatus
Receive status is not being checked.  We should probably check that and not send through if the status is bad.

2023-06-08 19:49 UTC, LeStarch commented on Drv/StreamCrossover/docs/sdd.md
> +| STREAM-CROSSOVER-COMP-001 | The stream crossover component shall provide the capability to forward bytes | inspection |
This requirement is now verified via unit-test.

2023-06-08 19:49 UTC, LeStarch commented on Drv/StreamCrossover/test/ut/Tester.cpp
> +    this->clearHistory();
You could put the requirement call here to make it easier to trace.

2023-06-09 21:29 UTC, LeStarch approved these changes

2023-06-09 22:22 UTC, thomas-bc approved these changes

2023-06-09 22:45 UTC, LeStarch approved these changes

2023-06-10 01:03 UTC, merged