Improve error display on failure
nasa/fprime pull request #2696
Opened 2024-04-17 21:54 UTC by JohanBertrand

| | |
|:---|:---|
|**_Related Issue(s)_**| https://github.com/nasa/fprime/issues/2695 |
|**_Has Unit Tests (y/n)_**| N/A |
|**_Documentation Included (y/n)_**| N/A |

---
## Change Description

- Remove stderr log line limit for print
- Display stdout log with before stderr log
- Add CI folder in the .gitignore

## Rationale

This will make debugging more easy when an error happen on the CI.

## Testing/Review Recommendations

N/A

## Future Work

N/A

2024-04-18 01:11 UTC, LeStarch requested changes

2024-04-18 01:11 UTC, LeStarch commented on ci/helpers.bash
> +        LASTLOG_OUT="${LASTLOG_ERR::-7}out.log" 1>&2
Is the 1>&2 here erroneous?  Otherwise the pr looks good.

2024-04-18 17:33 UTC, JohanBertrand commented on ci/helpers.bash
> +        LASTLOG_OUT="${LASTLOG_ERR::-7}out.log" 1>&2
Yes it is, thank you. It's fixed

2024-04-23 18:43 UTC, thomas-bc approved these changes

2024-04-23 22:51 UTC, LeStarch approved these changes

2024-04-23 22:51 UTC, merged