Update FPP to v2.1.0a11
nasa/fprime pull request #2745
Opened 2024-05-23 23:53 UTC by bocchino

* Update FPP to v2.1.0a11
* Make corresponding changes to client code

## FPP Changes

* Document dictionary generation in User's Guide by @bocchino in https://github.com/nasa/fpp/pull/422
* Update example in spec by @bocchino in https://github.com/nasa/fpp/pull/428
* Revise string code generation by @bocchino in https://github.com/nasa/fpp/pull/426
* Invalidate the buffer when sending a container by @bocchino in https://github.com/nasa/fpp/pull/427
* Add constant expressions for record sizes by @bocchino in https://github.com/nasa/fpp/pull/429
* Fixing removing the nullptr from join calls by @LeStarch in https://github.com/nasa/fpp/pull/425

2024-05-24 01:17 UTC, bocchino commented
CI is complaining because a link in a Markdown file in the cmake docs is unavailable. The issue is unrelated to this PR.

2024-05-24 18:03 UTC, LeStarch requested changes
Two minor comments, otherwise looks great!

2024-05-24 18:03 UTC, LeStarch commented on docs/Design/data-products.md
> +1. Standard F' components for managing data products.
This should say `F´`  not `F'`

2024-05-24 18:03 UTC, LeStarch commented on Fw/Types/test/ut/TypesTest.cpp
> +    ASSERT_EQ(strTmpl1, strTmpl2);
Shouldn't this test include a strTmpl1 is too large for the 40 test?
Why not use real strings rather than uninitialized strings.

2024-05-24 18:30 UTC, bocchino commented on Fw/Types/test/ut/TypesTest.cpp
> +    ASSERT_EQ(strTmpl1, strTmpl2);
Good points. I switched both strings to size 80 and initialized them. This corresponds to what we are doing for non-templated strings, and it seems good enough for a basic test that the template works.

2024-05-24 18:31 UTC, bocchino commented on docs/Design/data-products.md
> +1. Standard F' components for managing data products.
OK, I switched all instances of F' to F Prime, which I think is also acceptable. I have some questions about this, which we can resolve offline:
1. What is that forward tick character, and how do I type it?
2. Since forward tick seems to be a Unicode and not an ASCII character, is there a way to represent it in ASCII? Otherwise a Unicode text editor is required.
3. Why are we using forward tick instead of prime ' when we write F'?

2024-05-24 18:34 UTC, bocchino commented on docs/Design/data-products.md
> +1. Standard F' components for managing data products.
Note that if I were writing F' in Markdown as math I would write `_F'_` which resolves to _F'_.

2024-05-28 17:30 UTC, thomas-bc commented on docs/Design/data-products.md
> +1. Standard F' components for managing data products.
Rob, I forwarded you an email from Jeff regarding guidance on spelling F Prime, or F´ for short with the [prime symbol](https://en.wikipedia.org/wiki/Prime_(symbol)). This is what we are trying to adhere to. Both F´ or F Prime would work here.

On MacOS, the ´ character can be typed with Option+E.

2024-05-29 01:53 UTC, bocchino commented on docs/Design/data-products.md
> +1. Standard F' components for managing data products.
Thanks. Note that option-e generates an acute accent, not a prime symbol. There is a Unicode prime symbol, but it looks like it has no shortcut.

Single quote: F'
Prime symbol: Fʹ
Acute accent: F´

2024-06-04 16:07 UTC, thomas-bc commented
CI failure (markdown link not found) was fixed in https://github.com/nasa/fprime/pull/2746 and can safely be ignored

2024-06-04 16:11 UTC, thomas-bc approved these changes
LGTM! Ready to merge when we are

2024-06-04 17:14 UTC, LeStarch approved these changes

2024-06-04 17:14 UTC, merged