Issue #2727: Refactor System Resources OSAL Implmentation
nasa/fprime pull request #2922
Opened 2024-10-07 23:47 UTC by LeStarch

| | |
|:---|:---|
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---
## Change Description

Fixes issue #2727 by creating Os::Memory and Os::Cpu interfaces to support the non-filesystem aspects of SystemResources.

2024-10-08 01:23 UTC, LeStarch commented
@thomas-bc will you review?

2024-10-08 01:27 UTC, LeStarch commented
@bocchino will you review the use of templates here: https://github.com/nasa/fprime/blob/296aad01e2930bf20b083279fa1d556075ffaee7/Fw/Types/StringToNumber.cpp#L44-L73

I can make the argument it is a safe use of templates because: the template is not exposed to users, or outside code (it is implemented in the CPP).  The template is used as the implementation of a set of non-templated functions needed by the end user.

2024-10-08 22:16 UTC, bocchino approved these changes
I have reviewed the template usage. It looks good!

2024-10-08 23:12 UTC, thomas-bc requested changes

2024-10-08 23:12 UTC, thomas-bc commented on Fw/Types/StringToNumber.cpp
> +Fw::StringUtils::StringToNumberStatus string_to_helper_input_check(const CHAR* input, FwSizeType max_length, U8 base) {
Rename `max_length` to `buffer_size`

2024-10-08 23:12 UTC, thomas-bc commented on Fw/Types/StringToNumber.cpp
> +        FwSizeType length = Fw::StringUtils::string_length(input, max_length);
Rewrite comments for the `string_length` function and do no use / clarify `max_length`

2024-10-08 23:12 UTC, thomas-bc commented on Fw/Types/StringUtils.cpp
> +#include <cerrno>
delete these includes

2024-10-08 23:12 UTC, thomas-bc commented on Os/Darwin/Cpu.cpp
> +/**
Use `//!` style comments

2024-10-08 23:12 UTC, thomas-bc commented on Os/File.cpp
> +                size = j;
should be `j+1`

2024-10-08 23:12 UTC, thomas-bc commented on Os/Linux/Cpu.cpp
> +constexpr FwSizeType LINE_SIZE = 256; // log10(max(U64)) * 7 rounded to nearest power of 2
Could use some additional comments to explain what's going on and what it's going to be used for

2024-10-08 23:12 UTC, thomas-bc commented on Os/Stub/test/ut/StubFileTests.cpp
> +#include "Os/Models/Models.cpp"
remove all includes of `Models.cpp` (there's at least one other one than here)

2024-10-08 23:12 UTC, thomas-bc commented on cmake/platform/Linux.cmake
> +choose_fprime_implementation(Os/Cpu Os/Stub/Cpu)
Use Linux instead of Stub

2024-10-08 23:13 UTC, thomas-bc commented on cmake/platform/Linux.cmake
> +choose_fprime_implementation(Os/Cpu Os/Stub/Cpu)
Also add CMakePresets.json

2024-10-09 00:47 UTC, thomas-bc commented on CMakePresets.json
> +        "inherits": "fprime-ninja",
Should this be `"inherits": "fprime-debug",` instead, inheriting everything from UT and adding Ninja generator?

2024-10-09 00:47 UTC, thomas-bc commented on CMakePresets.json
> +        "inherits": "fprime-debug-ninja",
Same, `"inherits": "fprime-ut",`

2024-10-09 00:53 UTC, thomas-bc approved these changes

2024-10-09 04:29 UTC, merged