Bugfix/empty seq
nasa/fprime pull request #3025
Opened 2024-11-14 10:55 UTC by jsilveira1409

| | |
|:---|:---|
|**_Related Issue(s)_**| #3005  |
|**_Has Unit Tests (y/n)_**| n |
|**_Documentation Included (y/n)_**| n |

---
## Change Description

Implemented FileEmpty warning for the `Svc::CmdDispatcher` Component, which is called when deserializing the next record returns an empty buffer.

## Rationale
The Flight Software should raise a warning on empty command sequence files instead of crashing. 

## Testing/Review Recommendations

## Future Work

2024-11-14 17:33 UTC, LeStarch requested changes
A few minor changes and questions.

2024-11-14 17:33 UTC, LeStarch commented on Svc/CmdSequencer/Events.fppi
> +  #format "Sequence file {} is empty. Ignoring."
We need to clean-out the commented out code.  Preferably we'd include the sequence name.

What scenario would this hit?  Doesn't the sequence validation catch this (e.g. the CRC)?

Additionally, can this code be hit while a sequence is running? (e.g. the sequence file wasn't fully uplinked).

2024-11-14 17:34 UTC, LeStarch commented
@timcanham and @zimri-leisher I'd appreciate your thoughts on this PR.

2024-11-15 09:07 UTC, jsilveira1409 commented on Svc/CmdSequencer/Events.fppi
> +  #format "Sequence file {} is empty. Ignoring."
My bad for the comment, forgot about them!

`cmdSeq.CS_VALIDATE` does validate empty command sequences: 

![image](https://github.com/user-attachments/assets/9b430cb6-2bf7-4b61-ba84-0c368d4fd38b)

So actually the `CS_VALIDATE` would also need to trigger an empty command sequence event.

2024-11-15 09:20 UTC, jsilveira1409 commented on Svc/CmdSequencer/Events.fppi
> +  #format "Sequence file {} is empty. Ignoring."
So actually, to encompass both cases, a more elegant solution could be to simply verify the number of records when loading the sequence file at `FPrimeSequence` level, and return false if the number of records is zero, which would trigger the following events: 

![image](https://github.com/user-attachments/assets/9339d922-1f15-4ba6-8e08-53ae718bbbe4)

2024-11-15 15:10 UTC, zimri-leisher commented on Svc/CmdSequencer/Events.fppi
> +  #format "Sequence file {} is empty. Ignoring."
I think the FileEmpty solution may be technically inaccurate as the file still contains a sequence header and so is not literally empty. I like the second solution better, if this is the direction we choose to go.

2024-11-15 15:24 UTC, zimri-leisher commented
I would add/modify a unit test to check this behavior.

2024-11-15 16:58 UTC, jsilveira1409 commented
@zimri-leisher @LeStarch how about this event logs:

![image](https://github.com/user-attachments/assets/c32f88f1-a4f3-43bc-85ca-531b65b937d9)

2024-11-15 17:22 UTC, zimri-leisher commented
In my opinion this could be a low warning, but otherwise the event looks good! I assume it's the same for CS_VALIDATE.

2024-11-16 16:50 UTC, jsilveira1409 commented
@zimri-leisher yeah makes sense to make it low warning, here is the full logs with CS_VALIDATE too : 
![image](https://github.com/user-attachments/assets/47ee8685-fae9-4324-8aa2-4245cba5dc71)

2024-11-17 00:14 UTC, zimri-leisher commented
Looks good, just missing a unit test.

2024-11-17 18:29 UTC, zimri-leisher approved these changes

2024-11-18 01:27 UTC, timcanham approved these changes
LGTM!

2024-11-18 17:23 UTC, LeStarch approved these changes

2024-11-18 17:26 UTC, LeStarch commented
Looks good to me!  I added a commit to allow the improperly flagged misspellings.  Thanks for working this through!  @zimri-leisher thanks for the review!

2024-11-18 17:49 UTC, merged