lestarch: refactored IPv4 drivers
nasa/fprime pull request #354
Opened 2021-02-10 00:52 UTC by LeStarch

| | |
|:---|:---|
|**_Originating Project/Creator_**| Infrastructure |
|**_Affected Component_**| Drv  |
|**_Affected Architectures(s)_**| N/A |
|**_Related Issue(s)_**|   |
|**_Has Unit Tests (y/n)_**| y |
|**_Builds Without Errors (y/n)_**| y |
|**_Unit Tests Pass (y/n)_**| y |
|**_Documentation Included (y/n)_**|y  |

---
## Change Description

Refactors  SocketIpDriver into 3 specific drivers TcpClient, TcpServer, and Udp.

## Rationale

More reusability.

## Testing/Review Recommendations

## Future Work

Need to fix re-connection code.

2021-02-10 07:04 UTC, saba-ja requested changes

2021-02-10 07:04 UTC, saba-ja commented on Drv/Ip/IpSocket.cpp
> +#include <Fw/Types/StringUtils.hpp>
[Fw/Types/CMakeLists.txt](https://github.com/nasa/fprime/blob/update/ground-prototype/Fw/Types/CMakeLists.txt) needs to be updated with following lines:

https://github.com/nasa/fprime/blob/97883e50982a1275383a721f6c8a1c4c2aa1433e/Fw/Types/CMakeLists.txt#L20

https://github.com/nasa/fprime/blob/97883e50982a1275383a721f6c8a1c4c2aa1433e/Fw/Types/CMakeLists.txt#L35-L38

2021-02-10 16:11 UTC, LeStarch commented
Depends on #357 once that is merged we can continue with this PR.

2021-02-10 16:12 UTC, LeStarch commented on Drv/Ip/IpSocket.cpp
> +#include <Fw/Types/StringUtils.hpp>
See below, I created a PR for the Fw items.

2021-03-08 03:15 UTC, jsoref reviewed
Comparing https://github.com/check-spelling/fprime/commit/fd3268762bae962372a965d9454f084f6c9bf516#commitcomment-47976326 to 
https://github.com/check-spelling/fprime/pull/6#issuecomment-792427027

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/test/ut/SocketTestHelper.hpp
> + * Force a receive timeout on a socket such that it will not hang our testing despite the the normal recv behavor of
```suggestion
 * Force a receive timeout on a socket such that it will not hang our testing despite the the normal recv behavior of
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/IpSocket.hpp
> +     * `configure` method.  Tcp sockets will open bidirectional communication assuming the `condifure` function was
```suggestion
     * `configure` method.  Tcp sockets will open bidirectional communication assuming the `configure` function was
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/SocketReadTask.hpp
> +     * \brief constucts the socket read task
```suggestion
     * \brief constructs the socket read task
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/test/ut/TestTcp.cpp
> +TEST(Nominal, TestMulipleTcp) {
```suggestion
TEST(Nominal, TestMultipleTcp) {
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/test/ut/TestUdp.cpp
> +TEST(SingleSide, TestSingleSideMulipleUdp) {
```suggestion
TEST(Nominal, TestMultipleUdp) {
    test_with_loop(100, false);
}

TEST(SingleSide, TestSingleSideUdp) {
    test_with_loop(1, true);
}

TEST(SingleSide, TestSingleSideMultipleUdp) {
```

2021-03-08 03:15 UTC, jsoref commented on Drv/TcpClient/TcpClientComponentImpl.hpp
> +     * \paran port: port of remote tcp server
```suggestion
     * \param port: port of remote tcp server
```

2021-03-08 03:15 UTC, jsoref commented on Drv/TcpServer/TcpServerComponentImpl.hpp
> +     * \paran port: port of remote tcp server
```suggestion
     * \param port: port of remote tcp server
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Udp/UdpComponentImpl.hpp
> +     * \paran port: port of remote tcp server
```suggestion
     * \param port: port of remote tcp server
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Udp/UdpComponentImpl.hpp
> +     * \paran port: port of remote tcp server
```suggestion
     * \param port: port of remote tcp server
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/IpSocket.hpp
> +     * \param semd_timeout_microseconds: send timeout microseconds portion. Must be less than 1000000
```suggestion
     * \param send_timeout_microseconds: send timeout microseconds portion. Must be less than 1000000
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/UdpSocket.hpp
> +     * \param semd_timeout_microseconds: send timeout microseconds portion. Must be less than 1000000
```suggestion
     * \param send_timeout_microseconds: send timeout microseconds portion. Must be less than 1000000
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/UdpSocket.hpp
> +     * \param semd_timeout_microseconds: send timeout microseconds portion. Must be less than 1000000
```suggestion
     * \param send_timeout_microseconds: send timeout microseconds portion. Must be less than 1000000
```

2021-03-08 03:15 UTC, jsoref commented on Drv/TcpServer/docs/sdd.md
> +Drv::TcpServerComponentImpl comm = Drv::TcpServeromponentImpl("TCP Server");
```suggestion
Drv::TcpServerComponentImpl comm = Drv::TcpServerComponentImpl("TCP Server");
```

2021-03-08 03:15 UTC, jsoref commented on Drv/Ip/SocketReadTask.cpp
> +};  // namespace Drv
New line at eof to make tools happy

2021-03-08 03:15 UTC, jsoref commented on Drv/TcpServer/TcpServerComponentImpl.hpp
> +     * \return status of startup. SOCK_SUCCESS on success, somtheing else on error.
```suggestion
     * \return status of startup. SOCK_SUCCESS on success, something else on error.
```

2021-03-08 16:13 UTC, closed without merging